In [1]:
#1d array 
import numpy as np
a1 = np.array([2,4,6,8])
a1

array([2, 4, 6, 8])

In [2]:
print(a1)
print(a1/2)
print(a1*2)

[2 4 6 8]
[1. 2. 3. 4.]
[ 4  8 12 16]


In [6]:
#2d array 
import numpy as np 
a2 = np.array([[2,4,6,8],[10,12,14,16]])
print(a2)

[[ 2  4  6  8]
 [10 12 14 16]]


In [14]:
#3d array 
import numpy as np 
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
import numpy as np
from numpy.linalg import det 
mat1 = np.array([[1,2,3],[4,5,6],[7,8,1]])
print("Matrix:\n",mat1)
print("Determinant of mat1:",end=" ")
det1 = det(mat1)
print('%d'%det1)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 1]]
Determinant of mat1: 23


In [13]:
import numpy as np
from numpy.linalg import inv 
mat1 = np.array([[1,2,3],[4,5,6],[7,8,1]])
print("Matrix:\n")
print("Inverse of mat1:")
inv1 = inv(mat1)
print(inv1)

Matrix:

Inverse of mat1:
[[-1.79166667  0.91666667 -0.125     ]
 [ 1.58333333 -0.83333333  0.25      ]
 [-0.125       0.25       -0.125     ]]
